### ISSUE TITLE
Upload problem Windows 8.1 OBS Studio

### ISSUE THREAD

**Issue by mholoubek** [elan-ev/opencast-obs-plugin#1]
Hi

When i start the upload of a recording to my Opencast server i get the Error Message attached
There is no more information, just the popup.

System: Windows 8.1 Pro, OBS Studio 21.0.1 (64Bit), Opencast (v.4.0.0 - build: 77e712a)

BTW .... thank you for the plugin, it will be extremly helpfull :)

![error](https://user-images.githubusercontent.com/5603935/36251703-66d0c13c-1242-11e8-9491-39465bcb34bd.jpg)

**Comment by mholoubek** [comment]
With a trailing slash in the host url the error message changes to the one below.

![error_1](https://user-images.githubusercontent.com/5603935/36256198-2f2560de-1252-11e8-9946-00c28ed77cee.jpg)

It works if i use DIGESTAUTH instead of basic auth in the plugin settings.

**Comment by darolfes** [comment]
Hello,

Thank you for the (two) bugreports.

As you already know the first bug appears when the trailing slash is missing. As a workaround until the bug is fixed just add a trailing slash.

**Comment by darolfes** [comment]
I created a seperate issue for the first bug #2

**Comment by darolfes** [comment]
Sadly the BASICAUTH Authentication-Method is currently not finished, I forgot to remove the option. Sorry for the confusion.

**Comment by darolfes** [comment]
seperate issue #3

**Comment by mholoubek** [comment]
no problem and everything else is working so far. thanks!
